# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""
Utilities for computing wavelength lookup tables.
"""

import warnings

import numpy as np
import sciline as sl
import scipp as sc
from scippneutron.tof import chopper_cascade

from ..nexus.types import AnyRun, DiskChoppers
from .types import (
    DistanceResolution,
    LookupTable,
    LtotalRange,
    PulsePeriod,
    PulseStride,
    SourcePosition,
    SourcePulse,
    TimeResolution,
)


def _polygon_edges(polygons: list[np.ndarray]) -> np.ndarray:
    """
    Convert a list of polygons (N_i, 2) arrays to a single array of edges (E, 2, 2).
    """
    # polygons: list of (N_i, 2) arrays
    edges = []
    for poly in polygons:
        p1 = poly
        p2 = np.roll(poly, -1, axis=0)
        edges.append(np.stack([p1, p2], axis=1))  # (N, 2, 2)
    return np.concatenate(edges, axis=0)  # (E, 2, 2)


def _polygon_intersections(polygons: list[np.ndarray], xs: np.ndarray) -> np.ndarray:
    """
    Find the intersections of a list of polygons with vertical lines at specified x
    coordinates.
    We then take the mean of the minimum and maximum intersection points as an estimate
    of the mean wavelength in each bin. This handles the case where there are multiple
    subframes overlapping in a single time bin.

    Parameters
    ----------
    polygons:
        List of polygons, each represented as an (N_i, 2) array of vertices.
    xs:
        Array of x coordinates where intersections should be computed.

    Returns
    -------
    Array of intersection y coordinates, one for each x in `xs`.
    """
    edges = _polygon_edges(polygons)

    x1 = edges[:, 0, 0][:, None]  # (E, 1)
    y1 = edges[:, 0, 1][:, None]
    x2 = edges[:, 1, 0][:, None]
    y2 = edges[:, 1, 1][:, None]

    xs = xs[None, :]  # (1, N)

    # mask: edge crosses vertical line at x
    mask = ((x1 <= xs) & (x2 > xs)) | ((x2 <= xs) & (x1 > xs))

    # avoid division by zero (vertical edges won't pass mask anyway)
    denom = x2 - x1
    denom = np.where(denom == 0, np.nan, denom)

    t = (xs - x1) / denom
    y = y1 + t * (y2 - y1)

    # keep only valid intersections
    y = np.where(mask, y, np.nan)

    # now reduce along edges axis
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore", category=RuntimeWarning, message="All-NaN slice encountered"
        )
        y_min = np.nanmin(y, axis=0)
        y_max = np.nanmax(y, axis=0)

    # Value and spread estimate
    return 0.5 * (y_min + y_max), 0.5 * (y_max - y_min)


def _compute_mean_wavelength(
    subframes: list[chopper_cascade.Subframe],
    time_edges: sc.Variable,
    time_unit: str,
    frame_period: sc.Variable,
) -> sc.DataArray:
    """
    Compute the mean wavelength inside event_time_offset bins for a given range of
    distances.

    This is done by finding the intersection of the edges of the subframe polygons
    (generated by the ``chopper_cascade`` module) with vertical lines at the specified
    time edges.
    We then take the mean of the minimum and maximum intersection points as an estimate
    of the mean wavelength in each bin. This handles the case where there are multiple
    subframes overlapping in a single time bin.

    Parameters
    ----------
    subframes:
        List of subframes to consider. These should already be propagated to the
        correct distance.
    time_edges:
        Edges of the time bins for which to compute the mean wavelength. Should be a
        1D variable with a unit of time.
    time_unit:
        Unit to use for all time quantities.
    frame_period:
        Period of the source pulses, used to handle the periodicity of the subframes.
    """

    # To handle the periodicity of the subframes, we need to consider not only the
    # original subframes, but also copies of the subframes shifted by the frame period.
    # This is because neutrons that arrive after the frame period will wrap around and
    # appear in the next pulse, which is equivalent to the original pulse but shifted
    # by the frame period.
    polygons = [
        np.stack([f.time.to(unit=time_unit).values, f.wavelength.values], axis=1)
        for f in subframes
    ] + [
        np.stack(
            [(f.time.to(unit=time_unit) - frame_period).values, f.wavelength.values],
            axis=1,
        )
        for f in subframes
    ]

    wavs, stddevs = _polygon_intersections(polygons, time_edges.values)

    return sc.array(
        dims=time_edges.dims,
        values=wavs,
        variances=stddevs**2,
        unit=subframes[0].wavelength.unit,
    )


def _compute_frame_sequence(
    pulse_period: sc.Variable,
    disk_choppers: DiskChoppers[AnyRun],
    source_position: SourcePosition,
    source_pulse: SourcePulse,
    pulse_stride: PulseStride,
) -> chopper_cascade.FrameSequence:

    # The time_offset_open and time_offset_close below require the pulse_frequency to
    # be an integer multiple of the pulse frequency or vice versa. A simple trick is
    # to make sure that the requested pulse frequency is divided by an even number.
    div = pulse_stride + 1 if pulse_stride % 2 == 1 else pulse_stride
    # The `pulse_frequency` parameter in time_offset_open and time_offset_close below
    # decides how many rotations the chopper will perform when computing the open and
    # close times. Because we want to cover a number of pulses equal to `pulse_stride`,
    # we need to set the pulse frequency to be `pulse_stride` times smaller than the
    # actual pulse frequency.
    frequency_for_chopper_rotation = (1.0 / pulse_period.to(unit='s')) / div

    chops = {
        key: chopper_cascade.Chopper(
            distance=(ch.axle_position - source_position).fields.z,
            time_open=ch.time_offset_open(
                pulse_frequency=frequency_for_chopper_rotation
            ),
            time_close=ch.time_offset_close(
                pulse_frequency=frequency_for_chopper_rotation
            ),
        )
        for key, ch in disk_choppers.items()
    }

    frames = chopper_cascade.FrameSequence.from_source_pulse(
        time_min=source_pulse.time[0],
        time_max=source_pulse.time[1],
        wavelength_min=source_pulse.wavelength[0],
        wavelength_max=source_pulse.wavelength[1],
        pulse_period=pulse_period,
        npulses=pulse_stride,
    )
    frames = frames.chop(chops.values())
    return frames


def make_wavelength_lookup_table(
    choppers: DiskChoppers[AnyRun],
    source_pulse: SourcePulse,
    ltotal_range: LtotalRange,
    distance_resolution: DistanceResolution,
    time_resolution: TimeResolution,
    pulse_period: PulsePeriod,
    pulse_stride: PulseStride,
    source_position: SourcePosition,
) -> LookupTable:
    """
    Compute a lookup table for wavelength as a function of distance and
    time-of-arrival.

    Parameters
    ----------
    ltotal_range:
        Range of total flight path lengths from the source to the detector.
    distance_resolution:
        Resolution of the distance axis in the lookup table.
    time_resolution:
        Resolution of the time-of-arrival axis in the lookup table. Must be an integer.
    pulse_period:
        Period of the source pulses, i.e., time between consecutive pulse starts.
    pulse_stride:
        Stride of used pulses. Usually 1, but may be a small integer when
        pulse-skipping.
    """
    distance_unit = "m"
    time_unit = "us"
    res = distance_resolution.to(unit=distance_unit)
    pulse_period = pulse_period.to(unit=time_unit)
    frame_period = pulse_period * pulse_stride

    min_dist = ltotal_range[0].to(unit=distance_unit)
    max_dist = ltotal_range[1].to(unit=distance_unit)

    # We need to bin the data below, to compute the weighted mean of the wavelength.
    # This results in data with bin edges.
    # However, the 2d interpolator expects bin centers.
    # We want to give the 2d interpolator a table that covers the requested range,
    # hence we need to extend the range by at least half a resolution in each direction.
    # Then, we make the choice that the resolution in distance is the quantity that
    # should be preserved. Because the difference between min and max distance is
    # not necessarily an integer multiple of the resolution, we need to add a pad to
    # ensure that the last bin is not cut off. We want the upper edge to be higher than
    # the maximum distance, hence we pad with an additional 1.5 x resolution.
    pad = 2.0 * res
    distances = sc.arange('distance', min_dist - pad, max_dist + pad, res)

    # Create some time bins for event_time_offset.
    # We want our final table to strictly cover the range [0, frame_period].
    nbins = int(frame_period / time_resolution.to(unit=time_unit)) + 1
    time_edges = sc.linspace(
        'event_time_offset', 0.0, frame_period.value, nbins + 1, unit=pulse_period.unit
    )

    frames = _compute_frame_sequence(
        pulse_period=pulse_period,
        disk_choppers=choppers,
        source_position=source_position,
        source_pulse=source_pulse,
        pulse_stride=pulse_stride,
    )

    # Sort frames by reverse distance
    sorted_frames = sorted(frames, key=lambda x: x.distance.value, reverse=True)

    pieces = []
    # To avoid large RAM usage, and having to split the distances into chunks
    # according to which component reading to use, we simply loop over distances one
    # by one here.
    for dist in distances:
        # Find the correct simulation reading
        selected_frame = None
        for frame in sorted_frames:
            if dist.value >= frame.distance.to(unit=dist.unit).value:
                selected_frame = frame
                break
        if selected_frame is None:
            raise ValueError(
                "Building the lookup table failed: the requested position "
                f"{dist:c} is before the component with the lowest "
                "distance in the simulation. The first component in the beamline "
                f"has distance {sorted_frames[0].distance:c}."
            )

        subframes = selected_frame.propagate_to(dist).subframes

        pieces.append(
            _compute_mean_wavelength(
                subframes=subframes,
                time_edges=time_edges,
                time_unit=time_unit,
                frame_period=frame_period,
            )
        )

    table = sc.DataArray(
        data=sc.concat(pieces, 'distance'),
        coords={"distance": distances, "event_time_offset": time_edges},
    )

    return LookupTable(
        array=table,
        pulse_period=pulse_period,
        pulse_stride=pulse_stride,
        distance_resolution=table.coords["distance"][1] - table.coords["distance"][0],
        time_resolution=table.coords["event_time_offset"][1]
        - table.coords["event_time_offset"][0],
    )


def LookupTableWorkflow():
    """
    Create a workflow for computing a wavelength lookup table from a
    simulation of neutrons propagating through a chopper cascade.
    """
    wf = sl.Pipeline(
        (make_wavelength_lookup_table,),
        params={
            PulsePeriod: 1.0 / sc.scalar(14.0, unit="Hz"),
            PulseStride: 1,
            DistanceResolution: sc.scalar(0.1, unit="m"),
            TimeResolution: sc.scalar(250.0, unit='us'),
            SourcePulse: SourcePulse(
                time=(sc.scalar(0.0, unit='ms'), sc.scalar(4.0, unit='ms')),
                wavelength=(
                    sc.scalar(0.0, unit='angstrom'),
                    sc.scalar(15.0, unit='angstrom'),
                ),
            ),
        },
    )
    return wf
