# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: ess-developer

channels:
  - conda-forge
  - mantid
  - scipp
  - nodefaults

dependencies:
  - conda-build=3.23.3
  - flake8=6.0.0
  - gitpython=3.1.30
  - ipympl=0.9.2
  - ipython==8.5.0
  - mantid=6.5.0
  - nbsphinx=0.8.12
  - pandoc=2.19.2
  - pip=22.3.1
  - plopp=23.01.0
  - pooch=1.6.0
  - pytest=7.2.1
  - python-graphviz=0.20.1
  - pythreejs=2.4.1
  - scipp==22.11.0
  - scippneutron==22.12.4
  - sphinx=4.5.0
  - sphinx-book-theme=0.3.3
  - sphinx-copybutton=0.5.0
  - yapf=0.32.0
  - pip:
    - nb-clean==2.4.0
    - orsopy==1.0.1
    - sphinx-autodoc-typehints==1.18.3
