# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: ess-developer

channels:
  - conda-forge
  - mantid
  - scipp
  - nodefaults

dependencies:
  - conda-build=3.23.3
  - gitpython=3.1.32
  - ipympl=0.9.3
  - ipython==8.12.2
  - ipykernel==6.25.1
  - ipywidgets==8.1.0
  - mantid=6.7.0
  - nbsphinx=0.9.2
  - pandoc=3.1.3
  - pip=23.2.1
  - plopp=23.09.0
  - pooch=1.7.0
  - pytest=7.4.0
  - python=3.8.*
  - python-graphviz=0.20.1
  - pythreejs=2.4.2
  - scipp==23.08.0
  - scippneutron==23.09.0
  - scippnexus==23.08.0
  - sphinx=4.5.0
  - sphinx-book-theme=0.3.3
  - sphinx-copybutton=0.5.2
  - pip:
    - orsopy==1.0.1
    - sphinx-autodoc-typehints==1.18.3
