# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: ess-developer

channels:
  - conda-forge
  - mantid
  - scipp
  - nodefaults

dependencies:
  - black==23.3.0
  - conda-build=3.23.3
  - flake8=6.0.0
  - gitpython=3.1.30
  - ipympl=0.9.2
  - ipython==8.5.0
  - ipykernel==6.21.2
  - ipywidgets==8.0.4
  - mantid=6.6.0
  - nbsphinx=0.8.12
  - pandoc=2.19.2
  - pip=22.3.1
  - plopp=23.09.0
  - pooch=1.6.0
  - pytest=7.2.1
  - python=3.8.*
  - python-graphviz=0.20.1
  - pythreejs=2.4.1
  - scipp==23.08.0
  - scippneutron==23.09.0
  - scippnexus==23.08.0
  - sphinx=4.5.0
  - sphinx-book-theme=0.3.3
  - sphinx-copybutton=0.5.0
  - pip:
    - nb-clean==2.4.0
    - orsopy==1.0.1
    - sphinx-autodoc-typehints==1.18.3
