# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024 Scipp contributors (https://github.com/scipp)

# flake8: noqa
import importlib.metadata

try:
    __version__ = importlib.metadata.version(__package__ or __name__)
except importlib.metadata.PackageNotFoundError:
    __version__ = "0.0.0"

del importlib

from .base import (
    Analyzer,
    Cell,
    CellInBeamLog,
    CellSpinLog,
    Depolarized,
    DirectBeamBackgroundQRange,
    DirectBeamNoCell,
    DirectBeamQRange,
    Down,
    He3CellLength,
    He3CellPressure,
    He3DirectBeam,
    He3FillingTime,
    He3OpacityFunction,
    He3Polarization,
    He3Transmission,
    He3TransmissionEmptyGlass,
    PolarizationCorrectedSampleData,
    Polarized,
    Polarizer,
    RunSectionLog,
    SampleInBeamLog,
    Up,
    WavelengthBins,
    correct_sample_data_for_polarization,
    determine_run_section,
    direct_beam,
    direct_beam_with_cell,
    extract_analyzer_direct_beam_polarized,
    extract_direct_beam,
    extract_polarizer_direct_beam_polarized,
    extract_sample_data_down_down,
    extract_sample_data_down_up,
    extract_sample_data_up_down,
    extract_sample_data_up_up,
    he3_opacity_from_beam_data,
    he3_opacity_from_cell_params,
    he3_polarization,
    he3_transmission,
    providers,
    run_reduction_workflow,
)

__all__ = [
    "providers",
    "detect_run_section",
    "run_reduction_workflow",
    "determine_run_section",
    "direct_beam",
    "direct_beam_with_cell",
    "extract_direct_beam",
    "extract_polarizer_direct_beam_polarized",
    "extract_analyzer_direct_beam_polarized",
    "extract_sample_data_down_down",
    "extract_sample_data_down_up",
    "extract_sample_data_up_down",
    "extract_sample_data_up_up",
    "he3_transmission",
    "he3_opacity_from_beam_data",
    "he3_opacity_from_cell_params",
    "he3_polarization",
    "correct_sample_data_for_polarization",
    "Up",
    "Down",
    "Depolarized",
    "Polarized",
    "Analyzer",
    "Polarizer",
    "Cell",
    "WavelengthBins",
    "DirectBeamQRange",
    "DirectBeamBackgroundQRange",
    "He3Polarization",
    "He3Transmission",
    "He3CellPressure",
    "He3CellLength",
    "He3FillingTime",
    "He3OpacityFunction",
    "He3TransmissionEmptyGlass",
    "DirectBeamNoCell",
    "He3DirectBeam",
    "PolarizationCorrectedSampleData",
    "CellSpinLog",
    "RunSectionLog",
    "SampleInBeamLog",
    "CellInBeamLog",
]
