package:
  name: essimaging

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.10

  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package }}{% endif %}
  {% endfor %}


test:
  imports:
    - ess.imaging
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/essimaging
  license: BSD-3-Clause
  summary: Imaging data reduction for the European Spallation Source
  description: Imaging data reduction for the European Spallation Source
  dev_url: https://github.com/scipp/essimaging
  doc_url: https://scipp.github.io/essimaging
