# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

package:
  name: ess
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - ipywidgets
    - matplotlib
    - pooch
    - scippneutron>=22.12.4

test:
  imports:
    - ess
    - ess.wfm
    - ess.amor
    - ess.reflectometry
    - ess.sans
    - ess.loki

build:
  noarch: python
  script:
    - pip install .

about:
  home: https://github.com/scipp/ess
  license: BSD-3-Clause
  summary: Neutron scattering tools for the European Spallation Source (ESS)
  description: Neutron scattering tools for Data Reduction bespoke to ESS facility and instruments
  dev_url: https://github.com/scipp/ess
  doc_url: https://scipp.github.io/ess
