from argparse import ArgumentParser

import tomli

parser = ArgumentParser()
parser.add_argument(
    "--nightly",
    default="",
    help="List of dependencies to install from main branch for nightly tests, "
    "separated by commas.",
)
args = parser.parse_args()

header = "# Generated by 'tox -e deps', DO NOT EDIT MANUALLY!'\n"

with open("../pyproject.toml", "rb") as toml_file:
    pyproject = tomli.load(toml_file)
    dependencies = pyproject["project"].get("dependencies")
    if not dependencies:
        raise RuntimeError("No dependencies found in pyproject.toml")
    dependencies = [dep.strip().strip('"') for dep in dependencies]

with open("base.in", "w") as f:
    f.write(header)
    f.write("\n".join(dependencies))


def as_nightly(name: str) -> str:
    if name == "scipp":
        return "https://github.com/scipp/scipp/releases/download/nightly/scipp-nightly-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"  # noqa: E501
    return f"{name} @ git+https://github.com/scipp/{name}@main"


nightly = args.nightly.split(",")
dependencies = [dep for dep in dependencies if not dep.startswith(tuple(nightly))]
dependencies += [as_nightly(arg) for arg in nightly]

with open("nightly.in", "w") as f:
    f.write(header)
    f.write("\n".join(dependencies))
