import re
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument(
    "--nightly",
    default="",
    help="List of dependencies to install from main branch for nightly tests, "
    "separated by commas.",
)
args = parser.parse_args()

header = "# Generated by 'tox -e deps', DO NOT EDIT MANUALLY!'\n"

dependencies = []
with open("base.in", "w") as f:
    f.write(header)
    with open("../pyproject.toml", "r") as toml_file:
        toml_contents = toml_file.read()
        match = re.search(r"dependencies = \[(.*?)\]", toml_contents, re.DOTALL)
        if match:
            for dependency in match.group(1).split(",\n"):
                dependency = dependency.strip().strip('"')
                if dependency:
                    dependencies.append(dependency)
                    f.write(dependency + "\n")

nightly = args.nightly.split(",")

with open("nightly.in", "w") as f:
    f.write(header)
    for dependency in dependencies:
        for arg in nightly:
            if dependency.startswith(arg):
                f.write(f"{arg} @ git+https://github.com/scipp/{arg}@main" + "\n")
                break
        else:
            f.write(dependency + "\n")
