trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_main: $[eq(variables['System.PullRequest.TargetBranch'], 'main')]
  is_next: $[eq(variables['System.PullRequest.TargetBranch'], 'next')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:
  - stage: 'test'
    displayName: 'python tests'

    jobs:
      - job: 'python_test'
        displayName: 'Python tests'
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          ${{ if eq( variables['System.PullRequest.TargetBranch'], 'main' ) }}:
            - bash: |
               set -ex
               echo as main
               echo is master $(is_main)
               echo is next $(is_next)
               echo target branch $(System.PullRequest.TargetBranch)
          ${{ if eq( variables['System.PullRequest.TargetBranch'], 'next' ) }}:
            - bash: |
               set -ex
               echo as next
               echo is master $(is_main)
               echo is next $(is_next)
               echo target branch $(System.PullRequest.TargetBranch)

