name: Deploy docs

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: 'Select which package to build docs for'
      publish:
        default: false
        type: boolean
      branch:
        description: 'Branch/tag with documentation source. If not set, the main branch will be used.'
        default: 'main'
        required: false
        type: string

jobs:
  docs:
    name: Build and deploy docs
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          environments: docs-${{ inputs.package }}
      - name: Build docs
        run: pixi run docs-${{ inputs.package }}}}
      - name: Prepare site
        if: ${{ inputs.publish }}
        run: |
          PACKAGE=${{ inputs.package }}
          git fetch origin gh-pages:gh-pages || true
          git worktree add gh-pages-site gh-pages || mkdir -p gh-pages-site
          rm -rf gh-pages-site/$PACKAGE
          cp -r packages/$PACKAGE/html gh-pages-site/$PACKAGE
          cp docs/index.html gh-pages-site/index.html
          touch gh-pages-site/.nojekyll
      - name: Build search index
        if: ${{ inputs.publish }}
        run: npx pagefind@latest --site gh-pages-site --bundle-dir pagefind
      - uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ inputs.publish }}
        with:
          branch: gh-pages
          folder: gh-pages-site
      - uses: actions/upload-artifact@v4
        with:
          name: docs-${{ inputs.package }}
          path: packages/${{ inputs.package }}/html
