name: Nightly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * 1-5"

jobs:
  test:
    name: Nightly ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - essreduce
          - essimaging
          - essnmx
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          environments: ${{ matrix.package }}
      - name: Run tests
        run: pixi run -e ${{ matrix.package }} test ${{ matrix.package }}

  lower-bound:
    name: Lower bound ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - essreduce
          - essimaging
          - essnmx
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          environments: lb-${{ matrix.package }}
      - name: Test with lowest direct dependencies
        run: pixi run -e lb-${{ matrix.package }} test ${{ matrix.package }}

  unpinned:
    name: Unpinned Test ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - essreduce
          - essimaging
          - essnmx
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          environments: ess-unpinned
      - name: Test with latest dependencies
        run: pixi run -e ess-unpinned pytest packages/${{ matrix.package }}/tests
