name: Nightly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * 1-5"

env:
  PIXI_FROZEN: true
  PIXI_NO_INSTALL: true

jobs:
  test:
    name: Nightly ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - essreduce
          - essimaging
          - essnmx
          - essdiffraction
          - essreflectometry
          - esssans
          - essspectroscopy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.68.0
          frozen: true
          environments: ${{ matrix.package }}
      - name: Run tests
        run: pixi run -e ${{ matrix.package }} test ${{ matrix.package }}

  lower-bound:
    name: Lower bound ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - essreduce
          - essimaging
          - essnmx
          - essdiffraction
          - essreflectometry
          - esssans
          - essspectroscopy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.7.21"
          python-version: "3.11"
          cache-suffix: ${{ matrix.package }}
      - name: Test with lowest direct dependencies
        working-directory: packages/${{ matrix.package }}
        run: uv run --extra=test --resolution=lowest-direct pytest

  latest-dependencies:
    name: Latest dependencies ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - essreduce
          - essimaging
          - essnmx
          - essdiffraction
          - essreflectometry
          - esssans
          - essspectroscopy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.7.21"
          python-version: "3.11"
          cache-suffix: ${{ matrix.package }}
      - name: Test with latest dependencies
        working-directory: packages/${{ matrix.package }}
        run: uv run --extra=test --resolution=highest pytest
