name: PR and Main

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true  # cancel jobs from previous push

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # Run this before any other commands so that git diff does not pick up formatting changes.
      - run: |
          find . -type f -not -path '.git/*' -exec sed -ri "s/[0-9]{4} (Scipp contributors)/$(date +%Y) \1/g" {} +
          git diff --exit-code
      - run: pip install flake8==4.0.1 nb-clean==2.1.0 yapf==0.32.0
      - run: find . -type f -regex '.*\.ipynb' | xargs nb-clean clean --remove-empty-cells --preserve-cell-metadata
      - run: yapf --recursive --in-place .
      - run: flake8 .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic formatting

  # conda_build:
  #   needs: formatting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0  # history required so cmake can determine version
  #     - uses: conda-incubator/setup-miniconda@v2
  #     - run: conda install --channel conda-forge --yes conda-build mamba boa
  #     - run: conda mambabuild --channel conda-forge --channel scipp --channel mantid --no-anaconda-upload --override-channels --output-folder conda/package conda
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: conda-package-ess
  #         path: conda/package/*/ess*.tar.bz2

  tests_and_docs:
    needs: formatting
    runs-on: ubuntu-latest
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: .buildconfig/ci.yml
          activate-environment: ci
          auto-activate-base: false
      # - uses: actions/download-artifact@v2
      # - run: mamba install conda-package-*/*/*.tar.bz2
      - run: python -m pip install -e .
      - run: python -m pytest -v tests
      - run: python docs/make_docs.py

      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: ${{ env.DOCS_HTML_DIR }}
