# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Scipp contributors (https://github.com/scipp)

name: PR and Main

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true  # cancel jobs from previous push

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  formatting:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/static.txt
      - run: tox -e static
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic formatting

  tests_and_docs:
    needs: formatting
    name: ${{ matrix.os }}, py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-11", "windows-2019"]
        python-version: ["3.8"]
    env:
      JUPYTER_PLATFORM_DIRS: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # history required so cmake can determine version

      - name: Setup conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: 1.1.0
          environment-file: environment.yml
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}
            conda-build

      - run: conda develop src
      - run: jupyter --paths
      - run: python -m pytest -v tests
      - run: python docs/make_docs.py --build_dir=docs_html_${{ matrix.os }}

      - uses: actions/upload-artifact@v3
        if: ${{ contains(matrix.os, 'ubuntu') }}
        with:
          name: DocumentationHTML
          path: docs_html_${{ matrix.os }}
