# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Scipp contributors (https://github.com/scipp)

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:

  conda_build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  # history required so cmake can determine version

      - name: Setup conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: 1.1.0
          environment-file: false
          environment-name: build-release
          channels: conda-forge
          extra-specs: |
            python=3.8
            conda-build
            boa
      - run: conda mambabuild --channel conda-forge --channel scipp --channel mantid --no-anaconda-upload --override-channels --output-folder conda/package conda

      - uses: actions/upload-artifact@v3
        with:
          name: conda-package-ess
          path: conda/package/*/ess*.tar.bz2

  build_wheels:
    name: Wheels
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # history required so setuptools_scm can determine version

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/wheels.txt

      - name: Build wheels
        run: python -m build

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist


  tests_and_docs:
    needs: conda_build
    runs-on: ubuntu-latest
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: .buildconfig/ci.yml
          activate-environment: ci
          auto-activate-base: false
      - uses: actions/download-artifact@v2
      - run: mamba install conda-package-*/*/*.tar.bz2
      - run: python -m pytest -v tests
      - run: python docs/make_docs.py

      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: ${{ env.DOCS_HTML_DIR }}

  deploy_package:
    needs: tests_and_docs
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -c conda-forge --yes anaconda-client
      - uses: actions/download-artifact@v2
      - run: anaconda --token ${{ secrets.ANACONDATOKEN }} upload --user scipp --label main $(ls conda-package-*/*/*.tar.bz2)

  deploy_docs:
    needs: deploy_package
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1  # Avoid potential race condition when pushing to github pages
      matrix:
        docs-folder: ['latest', 'release']
    steps:
      - uses: actions/checkout@v2  # Need to checkout repo so github-pages-deploy-action works
      - uses: actions/download-artifact@v2
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: DocumentationHTML
          target-folder: ${{ matrix.docs-folder == 'latest' && format('release/{0}', github.ref_name) || '' }}
          single-commit: true
          clean-exclude: release
