name: Release

on:
  push:
    tags:
      - '*/[0-9]*'

jobs:
  determine-package:
    name: Determine package
    runs-on: ubuntu-24.04
    outputs:
      package: ${{ steps.parse.outputs.package }}
      version: ${{ steps.parse.outputs.version }}
    steps:
      - id: parse
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PACKAGE="${TAG%%/*}"
          VERSION="${TAG#*/}"
          echo "package=${PACKAGE}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ needs.determine-package.outputs.package }}
    needs: determine-package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build package
        run: pip install build && python -m build packages/${{ needs.determine-package.outputs.package }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish to PyPI
    needs: [determine-package, build]
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1

  docs:
    name: Publish docs
    needs: [determine-package, publish]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: docs-${{ needs.determine-package.outputs.package }}
      - name: Build docs
        run: pixi run -e docs-${{ needs.determine-package.outputs.package }} docs ${{ needs.determine-package.outputs.package }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/${{ needs.determine-package.outputs.package }}/html
          target-folder: ${{ needs.determine-package.outputs.package }}
