name: Weekly Platform Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

env:
  PIXI_FROZEN: true
  PIXI_NO_INSTALL: true

jobs:
  test:
    name: ${{ matrix.package }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        package:
          - essreduce
          - essimaging
          - essnmx
          - essdiffraction
          - essreflectometry
          - esssans
          - essspectroscopy
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.68.0
          frozen: true
          environments: ${{ matrix.package }}
      - name: Run tests
        run: pixi run -e ${{ matrix.package }} test ${{ matrix.package }}

  report-test-failure:
    name: Report weekly failures
    needs: test
    runs-on: ubuntu-slim
    if: failure() && github.event_name == 'schedule'
    env:
       GH_TOKEN: ${{ github.token }}
    permissions:
      # The weekly failure opens an issue.
      issues: write
    steps:
      - uses: actions/checkout@v6.1.0
      - name: Open an issue with the link to the failing test results.
        run: |
          number=$(gh issue list -l weekly-failure --json number -q ".[0].number")
          if [ -z ${number} ]; then
            today=$(date -I)
            title="Weekly Platform Test Failures ${today}"
            gh issue create -t "${title}" \
              -l weekly-failure \
              -b "See https://github.com/scipp/ess/actions/runs/${{ github.run_id }} for more details."
          else
            echo "An issue already exists for weekly failure: #${number}"
          fi

  report-test-success:
    name: Report weekly success
    needs: test
    runs-on: ubuntu-slim
    if: github.ref == 'refs/heads/main'
    env:
       GH_TOKEN: ${{ github.token }}
    permissions:
      # The weekly success closes an issue if needed.
      issues: write
    steps:
      - uses: actions/checkout@v6.1.0
      - name: Close the issue about the weekly failure.
        run: |
          number=$(gh issue list -l weekly-failure --json number -q ".[0].number")
          if [ -z ${number} ]; then
            echo "No issue opened."
          else
            gh issue close ${number} -r completed \
            -c "Weekly Platform tests fixed at https://github.com/scipp/ess/actions/runs/${{ github.run_id }}"
          fi
